name: flutter_app_trip
description: first flutter application

publish_to: 'none'
version: 1.1.0+5

environment:
  #  sdk: ">=2.8.0 <3.0.0" 2.12.0以上有了空安全要求

  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #城市列表,联系人列表,索引$悬停
  azlistview: ^2.0.0-nullsafety.0
  #苹果风格icon
  cupertino_icons: ^1.0.4
  #图片库
  cached_network_image: ^3.2.0
  #网络请求
  dio: ^4.0.4
  #Banner
  flutter_card_swipper: ^0.4.0
  #分页瀑布流
  flutter_staggered_grid_view: ^0.4.1
  #Toast
  fluttertoast: ^8.0.8
  #webview
  webview_flutter: ^3.0.0
  #汉字转拼音
  lpinyin: ^2.0.3
  #获取app信息插件
  package_info: ^2.0.2
  #json解析
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# 特定的flutter
flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/

